exp:
  backbone: resnet50
  checkpoint_dir: checkpoint
  tensorboard_dir: runs
  preds: preds
  cam: cam
  results: results
  final_weights: resnet_cam.pth

dataset:
  root_dir: /home/rlx/VOCdevkit/VOC2012
  txt_dir: dataset/voc
  n_classes: 20
  mean_bgr: [104.008, 116.669, 122.675]
  std_bgr: [104.008, 116.669, 122.675]

model:
  blocks: [3, 4, 23, 3]

train:
  split: train_aug
  batch_size: 16
  max_epochs: 6
  save_iters: 100
  crop_size: 512
  scales: [0.5, 0.75, 1.0, 1.25, 1.5]
  opt:
    learning_rate: 1e-2
    weight_decay: 1e-4
    momentum: 0.9
    power: 0.9

val:
  split: val

cam:
  split: val
  scales: [1.0, 0.5, 1.5, 2.0]
  bgscore: 0.14